#!/bin/bash
# Elyamany Linux Shell - Command Interpreter

echo "╔═══════════════════════════════════════════════╗"
echo "║  Elyamany Linux Shell (esh)                   ║"
echo "║  Version 1.0.0                               ║"
echo "╚═══════════════════════════════════════════════╝"
echo ""
echo "Available commands:"
echo "  help      - Show this help"
echo "  ls        - List files"
echo "  cd        - Change directory"
echo "  pwd       - Print working directory"
echo "  mkdir     - Create directory"
echo "  rm        - Remove files"
echo "  cat       - Display file contents"
echo "  echo      - Print text"
echo "  ps        - Show processes"
echo "  kill      - Terminate process"
echo "  mount     - Mount filesystem"
echo "  umount    - Unmount filesystem"
echo "  ip        - Network configuration"
echo "  shutdown  - Shutdown system"
echo "  reboot    - Reboot system"
echo ""
echo "Type 'command --help' for more information"
